version: "3.9"

services:
  php74:
    build:
      context: ./php/7.4
    volumes:
      - ${LEGACY_APP_HOST_PATH:-./sample-app}:/var/www/html
    environment:
      - PHP_IDE_CONFIG=serverName=php74

  php84:
    build:
      context: ./php/8.4
    volumes:
      - ${LEGACY_APP_HOST_PATH:-./sample-app}:/var/www/html
    environment:
      - PHP_IDE_CONFIG=serverName=php84

  web:
    image: nginx:alpine
    depends_on:
      - php74
      - php84
    ports:
      - "8080:80"
    environment:
      - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    command: /bin/sh -c "envsubst '$$PHP_VERSION' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
